services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env  # 👈 Add this line to load environment variables properly
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env  # 👈 Add this to load DB credentials
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
