version: "3.8"

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      HOST: db                # Points to the 'db' service in Docker, not localhost
      DBNAME: ${DBNAME}         # Will be set by Render's environment variables
      USERNAME: ${USERNAME}         # Will be set by Render's environment variables
      PASSWORD: ${PASSWORD} # Will be set by Render's environment variables
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Set by Render environment variables
      MYSQL_DATABASE: ${DBNAME}                    # Set by Render environment variables
      MYSQL_USER: ${USERNAME}                        # Set by Render environment variables
      MYSQL_PASSWORD: ${PASSWORD}                # Set by Render environment variables
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
