version: "3.8"

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      HOST: dpg-cvhm5l1opnds73fl4170-a.oregon-postgres.render.com  # Matches Render.com
      DBNAME: inf653_ar_midterm_7e6a  # Matches Render.com
      USERNAME: inf653_ar_midterm_7e6a_user  # Matches Render.com
      PASSWORD: 5zCP7GMDvHwtrpXF9D0hpgWFr6TGpQSu  # Matches Render.com
      PORT: "5432"  # Matches Render.com
    depends_on:
      - db

  db:
    image: postgres:16  # PostgreSQL 16 (latest stable version)
    restart: always
    environment:
      POSTGRES_DB: inf653_ar_midterm_7e6a
      POSTGRES_USER: inf653_ar_midterm_7e6a_user
      POSTGRES_PASSWORD: 5zCP7GMDvHwtrpXF9D0hpgWFr6TGpQSu
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:

